os: Visual Studio 2015
install:
  - choco install gitversion.portable -pre -y
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build: 
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo src\PdfSharper\Properties\AssemblyInfo.cs

build:
  project: src\BuildAll-PdfSharp.sln