configuration: Release
platform: Any CPU

install:
  - choco install gitversion.portable -pre -y

before_build: 
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo src\PdfSharper\Properties\AssemblyInfo.cs
  - nuget restore src\BuildAll-PdfSharp.sln

build:
  project: src\BuildAll-PdfSharp.sln